name: Update configuration files

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call-update-configuration-files:
    name: Update configuration files
    uses: actions/reusable-workflows/.github/workflows/update-config-files.yml@main
